version: '3'
services:
  tomcat:
    image: tomcat:9-jdk11-corretto-al2
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/usr/local/tomcat/webapps
      - ./server.xml:/usr/local/tomcat/conf/server.xml